# Generated by Django 3.2.6 on 2021-08-20 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_name', models.CharField(max_length=100, null=True)),
                ('Car_model', models.CharField(max_length=100, null=True)),
                ('Car_Part_Name', models.CharField(max_length=100, null=True)),
                ('Car_Part_Info', models.CharField(choices=[('New', 'New'), ('Use', 'Use')], max_length=50)),
                ('Car_Part_Discription', models.CharField(max_length=100, null=True)),
                ('Owner_info', models.CharField(max_length=200, null=True)),
                ('Part_Image', models.ImageField(upload_to='images/')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Car_Part_App.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Car_Part_App', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
